version: '3.1'
services:
  cupsd:
    container_name: cupsd
    build: cupsd-php-apache
#   Comment out ports for production
#    ports:
#      - "632:631"
#      - "8081:80"
    volumes:
      - ./config.ini:/var/www/config.ini
      - ./html:/var/www/html
      - ./cups-config/printers.conf:/etc/cups/printers.conf
      - ./cups-config/ppd:/etc/cups/ppd
      - ./cups-config/ssl:/etc/cups/ssl
      - ./pdfs:/pdfs

networks:
  default:
    external:
      name: redcapprod_redcap_prod
